name: Check - Sanity Tests

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - labeled

jobs:
  run:
    uses: ./.github/workflows/playwright-base.yml
    with:
      test-command: --grep @sanity
      blob-name: sanity
      retention-days: 1
      fetch-depth: 0
      html-report: on-failure
      monocart-report: never
      allure-report: never
      blob-report: never